# Generated by Django 4.2.3 on 2023-08-30 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apps", "0002_projects"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tech",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("image", models.ImageField(upload_to="pics")),
                ("descriptions", models.TextField()),
            ],
        ),
    ]
