# Generated by Django 4.2.3 on 2023-08-31 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apps", "0003_tech"),
    ]

    operations = [
        migrations.CreateModel(
            name="CallBackRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("mobile", models.CharField(max_length=20)),
                ("subject", models.CharField(max_length=200)),
                ("message", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("exported", models.BooleanField(default=False)),
            ],
        ),
    ]
